### ISSUE TITLE
Geotraitement - Centroide

### ISSUE THREAD

**Issue by TERMEPhilippe** [atolcd/pentaho-gis-plugins#16]
Le Geotraitement Centroide renvoi invariablement un message d'erreur

Géotraitement.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Erreur inattendue
2017/08/16 11:11:55 - Géotraitement.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : java.lang.ArrayIndexOutOfBoundsException: -1
2017/08/16 11:11:55 - Géotraitement.0 - 	at com.atolcd.pentaho.di.trans.steps.gisgeoprocessing.GisGeoprocessing.processRow(GisGeoprocessing.java:337)
2017/08/16 11:11:55 - Géotraitement.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2017/08/16 11:11:55 - Géotraitement.0 - 	at java.lang.Thread.run(Thread.java:748)

PDI ; Version 7.1
Plugin GIS : 1.2.1

**Comment by roboguy** [comment]
@TERMEPhilippe - Can you attach your transformation ?

**Comment by TERMEPhilippe** [comment]
Le problème vient d'un mauvais paramétrage de ma part. Le champ "Résultat" doit être renseigné puis converti en type Geometry pour pouvoir être compris.
Sorry.
![centroide](https://user-images.githubusercontent.com/6795250/29416746-5fc4d91a-8367-11e7-9458-ed1d44fd886c.PNG)
