### ISSUE TITLE
VFS error

### ISSUE THREAD

**Issue by dwadmin49** [atolcd/pentaho-gis-plugins#18]
_Pentaho : 8.0.0.0-28
PDI GIS plugin : 1.2.1_

Bonjour. Je viens de tester une transformation toute simple composée d'un import d'une table PostGIS et d'un export de fichier shape (GIS File Output). L'erreur suivante est apparue : 

```
2018/03/19 09:33:16 - GIS File output.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : Unexpected error
2018/03/19 09:33:16 - GIS File output.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : java.lang.NoSuchMethodError: org.pentaho.di.core.vfs.KettleVFS.getFileObject(Ljava/lang/String;)Lorg/apache/commons/vfs/FileObject;
2018/03/19 09:33:16 - GIS File output.0 - 	at com.atolcd.pentaho.di.gis.io.AbstractFileWriter.checkFilename(AbstractFileWriter.java:63)
2018/03/19 09:33:16 - GIS File output.0 - 	at com.atolcd.pentaho.di.gis.io.ShapefileWriter.<init>(ShapefileWriter.java:77)
2018/03/19 09:33:16 - GIS File output.0 - 	at com.atolcd.pentaho.di.trans.steps.gisfileoutput.GisFileOutput.processRow(GisFileOutput.java:73)
2018/03/19 09:33:16 - GIS File output.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2018/03/19 09:33:16 - GIS File output.0 - 	at java.lang.Thread.run(Unknown Source)
```

Du coup, je me demande si le plug-in est compatible avec ma version de pdi ou non ?

**Comment by codek** [comment]
The PDI GIS plugin just needs to be re-compiled for Apache VFS 2.0 . (just change references to vfs2 and it should work.)

http://pedroalves-bi.blogspot.co.uk/2015/10/pentaho-60-and-plugins-upgrade-from-vfs.html

Apologies for answering in english, i hope it translates ok!

**Comment by dwadmin49** [comment]
Thanks a lot. 

It should works but I finally found an other solution. In the compilation documentation, I read : 

> Note :
>
>    You can specify the target version of Pentaho with one of the available profiles : pentaho-5, >pentaho-6 or pentaho-7 (default). Example :
>
>      mvn clean package -Dpentaho=5
>
>The built package is target/pentaho-gis-plugins-1.2.1-bin-5.zip (version can differ)

Then I remember that my download link was : 

> https://github.com/atolcd/pentaho-gis-plugins/releases/download/v1.2.1/pentaho-gis-plugins-1.2.1-bin-5.zip

So, I've just replaced the  5 in the link with 7 (8 does not exists) and I've re-downloaded the plugins. After testing, all is ok !

**Comment by codek** [comment]
ah ha, yes, then that's exactly what the difference is :)
