### ISSUE TITLE
Coordinate System Operation Step Opening break

### ISSUE THREAD

**Issue by mamanso** [atolcd/pentaho-gis-plugins#2]
I have installed last version of PDI community and compiled PDI GIS Plugins with last version of maven for windows 32 bits, and jdk1.7.0_79

Compilation do break all it is correct and generate zip file with all of the pluging content.
After uncompress it in PDI_home/plugins/step and opening PDI Geospatial steps appear in PDI user interface.
I can make a new transformation and when i to concat a Coordinated system operation with an input step and try to open properties of that step a error windows appear. 
The first time of that error message title:
I was unable to create a dialog for step com.atolcd.pentaho.di.ui.trans.steps.giscoordinatetransformation.GisCoordinateTransformationDialog
And content:
loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/pentaho/di/core/plugins/KettleURLClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of java/net/URLClassLoader) for resolved class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type gerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory; used in the signature

The second on time trying to open properties of the step the message title is the same but the content is:
Could not initialize class org.cts.registry.RegistryManager

What can be the problem?

Best regards,
Miguel A. Manso

**Comment by cvagner** [comment]
Thank you.
The bug has been removed in the version 1.1-SNAPSHOT.

Two version of slf4j were used so that class loaders you mentioned weren't able to manage the LoggerFactory.
