### ISSUE TITLE
Geopackage input file

### ISSUE THREAD

**Issue by asensioj** [atolcd/pentaho-gis-plugins#21]
First of all thank you for this great extension.

I am new in pentaho and I am trying to manage spatial data. I have installed your extension both from marketplace and manually but I cannot see the option in the input file to open a Geopackage file. Did I miss something?

Thanks

**Comment by raiAtol** [comment]
Hello,

We are pleased that the steps might be useful.

We are working on adding Geopackage input/output to the plugin.

Stay tuned, it's on the way.
