### ISSUE TITLE
Download from Marketplace fails

### ISSUE THREAD

**Issue by sunils27** [atolcd/pentaho-gis-plugins#3]
The download of the plugins from marketplace fails. Also your instructions for manual installation do not work, probably for the same reason. 
The link to the zip file doesn't work. 

> wget https://github.com/atolcd/pentaho-gis-plugins/releases/download/v1.1-snapshot/pentaho-gis-plugins-1.1-SNAPSHOT-bin.zip
> --2015-11-02 13:27:58--  https://github.com/atolcd/pentaho-gis-plugins/releases/download/v1.1-snapshot/pentaho-gis-plugins-1.1-SNAPSHOT-bin.zip
> Resolving github.com (github.com)... 192.30.252.128
> Connecting to github.com (github.com)|192.30.252.128|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2015-11-02 13:27:58 ERROR 404: Not Found.

**Comment by cvagner** [comment]
sunils27,

The release was reset as a draft so that it wasn't available for download with the provided link anymore.
I published it again.

Thanks for your report.
