### ISSUE TITLE
How to create geometry field from longitude/latitude using JavaScript API

### ISSUE THREAD

**Issue by samtux** [atolcd/pentaho-gis-plugins#35]
I'm trying to create a geometry field using the Pentaho GIS plugin's JavaScript API in a "Modified JavaScript Value" step. I want to create a Point geometry from longitude and latitude fields.

Current setup:
- Pentaho Data Integration version: 9.4.0.0-343
- GIS Plugin installed from Marketplace
- Input fields: longitude (double), latitude (double)
- Target: PostgreSQL geometry field (SRID: 4326)

I've tried:
```javascript
var GisGeometry = Packages.com.atolcd.pentaho.di.gis.utils.GeometryUtils;
var geom = GisGeometry.createPoint(lon, lat, 4326);
```

![imagen](https://github.com/user-attachments/assets/136261b1-83b5-4a93-b45f-6606fffd32d0)

But I get this error:

TypeError: [JavaPackage org.pentaho.gis.geometry.GisGeometry] is not a function, it is object

Could you please provide an example of creating a Point geometry from coordinates from the CSV table.

Thank you for your help!

**Comment by darbonc** [comment]
You can create POINT geometry using WKT and transform the string with select step

![image](https://github.com/user-attachments/assets/984044ba-4713-4975-bb44-96a1e6dec3b8)

**Comment by samtux** [comment]
Thank you @darbonc  for this solution! I was overcomplicating things trying to use the JavaScript API, when the solution was as simple as using WKT format. Here’s the proof it works perfectly:

![imagen](https://github.com/user-attachments/assets/d5e04080-f255-4f9f-9716-88c7fafa459c)

**Comment by cvagner** [comment]
Nice. Thank you Cédric @darbonc!
