### ISSUE TITLE
Conversion Error Unknown type 43663879 specified.

### ISSUE THREAD

**Issue by roboguy** [atolcd/pentaho-gis-plugins#5]
While trying to write out geometries to a file or using in Pentaho's group by step, I encountered an issue with the Geometry column in preview data tab having a conversion error. 

dim | point
   2   | Conversion error: point Geometry : Unknown type 43663879 specified.

I have attached a KTR file that demonstrates the issue along with sample data. 
Please change the file extension of test_5.4.txt to ktr (github does not allow attaching of ktr files).

KTR File: [test_5.4.txt](https://github.com/atolcd/pentaho-gis-plugins/files/39741/test_5.4.txt)
Test Data: [data.txt](https://github.com/atolcd/pentaho-gis-plugins/files/39742/data.txt)

**Comment by gonzalomelov** [comment]
@roboguy How did you manage to solve this? I always get NULL when converting from TEXT to GEOMETRY type from a CSV.

**Comment by roboguy** [comment]
@gonzalomelov - is your text in WKT format in the csv file ? If so then it should work to read.
I have a code fix for it and I think its been merged here but i don't remember right away since its been a few years. I will check and let you know!

**Comment by gonzalomelov** [comment]
@roboguy  Thank you so much for your almost instant response!
I think I have everything OK (plugin installation, transformation, wkt in the csv file). Look the following screenshots:

<img width="452" alt="screen shot 2018-01-15 at 20 46 36" src="https://user-images.githubusercontent.com/1372744/34965809-b4da435a-fa35-11e7-8f50-ad3d5acd60f4.png">

<img width="936" alt="screen shot 2018-01-15 at 20 52 39" src="https://user-images.githubusercontent.com/1372744/34965851-0b29d7de-fa36-11e7-8314-64a483ed79ac.png">

<img width="1432" alt="screen shot 2018-01-15 at 20 47 53" src="https://user-images.githubusercontent.com/1372744/34965816-ccfee486-fa35-11e7-8343-32606fd7757c.png">

<img width="1176" alt="screen shot 2018-01-15 at 20 48 04" src="https://user-images.githubusercontent.com/1372744/34965817-d024d1b6-fa35-11e7-83af-a58f69d28073.png">
