### ISSUE TITLE
Marketplace: PDI GIS Plugins 

### ISSUE THREAD

**Issue by eddpascoal** [atolcd/pentaho-gis-plugins#6]
I'm using kettle version 6 and i can't install "PDI GIS Plugins". I try to install another plugin using marketplace and it works fine but when i try to install PDI GIS Plugins it fails occuring the following statement:
`Error occurred when installing plugin PDI GIS Plugins.[ Failed to execute install, see log for details.]`

Unfortunately i couldn't find where the log is to know which error is raising. It is available PDI GIS Plugins to kettle PDI v6? How can i install that?

I tried to install in Kettle PDI v5.4 and they couldn't find `https://github.com/atolcd/pentaho-gis-plugins/releases/download/v1.1-snapshot/pentaho-gis-plugins-1.1-SNAPSHOT-bin.zip` maybe should be `https://github.com/atolcd/pentaho-gis-plugins/archive/v1.0-snapshot.zip`

**Comment by tsykes** [comment]
I'd like to try this plugin as well but am running into the same issues. I'm planning an upgrade to Kettle 6.

**Comment by cvagner** [comment]
_Installation issue :_
Like issue #3 _Download from Marketplace fails_, the zip file wasn't available for download anymore. The internal automation issue has been fixed and it shouldn't happen anymore.

Thanks for the report.

_PDI 6 :_
Version 1.1 lacks a dependancy to run. I created the issue #7 _Make it compatible with PDI 6_
I will be fix as soon as possible.
