### ISSUE TITLE
PostGIS support?

### ISSUE THREAD

**Issue by tsykes** [atolcd/pentaho-gis-plugins#8]
Would PostGIS support be a reasonable thing to add? Perhaps I could lend a hand.

**Comment by darbonc** [comment]
PostGIS is already supported in steps : Table input, Table output, Insert / Update, Update, Database lookup, Database join.

**Comment by tsykes** [comment]
Thanks. The geometry data type showed up only after installing pentaho-gis-plugins, right? Otherwise, I'm a bit confused about not seeing it before. There are a lot of forum posts asking for this since the old GeoKettle.  This is great.
